FROM postgres:latest
LABEL key="aljuly"

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD passw0rd
# ENV POSTGRES_DB calculator
# COPY schema.sql /docker-entrypoint-initdb.d/
# COPY operations.sql /docker-entrypoint-initdb.d/
